# PROPERTIES USED IN CREATING THE SAML ASSERTION
ISSUER = "urn:ihe-europe:sts"
ORGANIZATION = ""
ORGANIZATION_ID = "urn:oid:"
HOME_COMMUNITY_ID = "urn:oid:"
CERT_SUBJECT = "CN=, OU=IT, O=, L=NewYork"
